export const AUTOMA_MOVE = 'AUTOMA_MOVE';
export const AUTOMA_BUILD = 'AUTOMA_BUILD';
export const AUTOMA_FINALISE = 'AUTOMA_FINALISE';
export const GAME_INITIATED = 'GAME_INITIATED';
export const COMBAT_INITIATED = 'COMBAT_INITIATED';
export const COMBAT_INPROGRESS = 'COMBAT_INPROGRESS';
export const COMPLETE = 'COMPLETE';
export const GAME_SETUP = 'GAME_SETUP';
