export const AUTOMA_MOVE_INPROGRESS = 'AUTOMA_MOVE_INPROGRESS';
export const AUTOMA_ACTION_INPROGRESS = 'AUTOMA_ACTION_INPROGRESS';
export const GAME_INITIATED = 'GAME_INITIATED';
export const COMBAT_INITIATED = 'COMBAT_INITIATED';
export const COMBAT_INPROGRESS = 'COMBAT_INPROGRESS';
export const COMPLETE = 'COMPLETE';
